apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-storage-pvc
  namespace: alpa
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-nfs
  resources:
    requests:
      storage: 2Ti
