apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster-nfs-pv
spec:
  capacity:
    storage: 2Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-nfs
  nfs:
    path: /mnt/hdd2/cluster_dat
    server: 10.213.14.170
